name: login_flutter
description: A flutter login model app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4
  image_cropper: 5.0.1
  http: ^0.13.6
  crop: any
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
